import { combineEpics } from 'redux-observable';
import {
  fetchTableDataEpic,
  fetchAnalyticsEpic,
  fetchSummaryEpic,
  fetchCategoriesEpic,
  globalFilterChangeEpic,
  tableConfigChangeEpic,
  queryChangeEpic,
  createExpenseEpic,
  updateExpenseEpic,
  deleteExpenseEpic,
  undoEpic,
  bulkSyncEpic,
  fillMonthEpic,
  createCategoryEpic,
  updateCategoryEpic,
  deleteCategoryEpic,
  mergeCategoriesEpic,
  checkAuthSessionEpic,
  logoutEpic,
} from '../features/expenses/expensesEpics';

export const rootEpic = combineEpics(
  fetchTableDataEpic,
  fetchAnalyticsEpic,
  fetchSummaryEpic,
  fetchCategoriesEpic,
  globalFilterChangeEpic,
  tableConfigChangeEpic,
  queryChangeEpic,
  createExpenseEpic,
  updateExpenseEpic,
  deleteExpenseEpic,
  undoEpic,
  bulkSyncEpic,
  fillMonthEpic,
  createCategoryEpic,
  updateCategoryEpic,
  deleteCategoryEpic,
  mergeCategoriesEpic,
  checkAuthSessionEpic,
  logoutEpic,
);